apiVersion: v1
kind: Template
parameters:
  - name: SOURCE_REPOSITORY_URL
    description: The source URL for the application
    displayName: Source URL
    value: 'https://github.com/dummy_org/dummy_repo'
    required: true
  - name: GITHUB_WEBHOOK_SECRET
    description: The secret used to configure a GitHub webhook
    displayName: GitHub Webhook Secret
    required: true
    from: '[a-zA-Z0-9]{40}'
    generate: expression
objects:
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      name: openjdk18-openshift
      creationTimestamp: null
      labels:
        app: fuse-cxf-amq-example
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: latest
          from:
            kind: DockerImage
            name: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
          generation: null
          importPolicy: {}
          referencePolicy:
            type: ''
    status:
      dockerImageRepository: ''
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      name: fuse-cxf-amq-example
      creationTimestamp: null
      labels:
        app: fuse-cxf-amq-example
    spec:
      lookupPolicy:
        local: false
    status:
      dockerImageRepository: ''
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: fuse-cxf-amq-example
      creationTimestamp: null
      labels:
        app: fuse-cxf-amq-example
    spec:
      triggers:
        - type: GitHub
          github:
            secret: '${GITHUB_WEBHOOK_SECRET}'
        - type: ConfigChange
        - type: ImageChange
          imageChange: {}
      source:
        type: Git
        git:
          uri: '${SOURCE_REPOSITORY_URL}'
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: 'openjdk18-openshift:latest'
          incremental: true
          env: []
      output:
        to:
          kind: ImageStreamTag
          name: 'fuse-cxf-amq-example:latest'
      resources: {}
      postCommit: {}
      nodeSelector: null
    status:
      lastVersion: 0
  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      name: fuse-cxf-amq-example
      creationTimestamp: null
      labels:
        app: fuse-cxf-amq-example
    spec:
      strategy:
        resources: {}
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - fuse-cxf-amq-example
            from:
              kind: ImageStreamTag
              name: 'fuse-cxf-amq-example:latest'
      replicas: 1
      test: false
      selector:
        app: placeholder-app-label-d46881878f594a2dadfd963843452aab
        deploymentconfig: fuse-cxf-amq-example
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: placeholder-app-label-d46881878f594a2dadfd963843452aab
            deploymentconfig: fuse-cxf-amq-example
        spec:
          containers:
            - name: fuse-cxf-amq-example
              image: 'fuse-cxf-amq-example:latest'
              ports:
                - containerPort: 8080
                  protocol: TCP
                - containerPort: 8443
                  protocol: TCP
                - containerPort: 8778
                  protocol: TCP
              resources:
                limits:
                  memory: 1G
              env: []
              readinessProbe:
                httpGet:
                  path: /health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 5
                timeoutSeconds: 3
                periodSeconds: 10
                failureThreshold: 10
              livenessProbe:
                httpGet:
                  path: /health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 60
                timeoutSeconds: 3
    status:
      latestVersion: 0
      observedGeneration: 0
      replicas: 0
      updatedReplicas: 0
      availableReplicas: 0
      unavailableReplicas: 0
  - kind: Service
    apiVersion: v1
    metadata:
      name: fuse-cxf-amq-example
      creationTimestamp: null
      labels:
        app: fuse-cxf-amq-example
    spec:
      ports:
        - name: 8080-tcp
          protocol: TCP
          port: 8080
          targetPort: 8080
        - name: 8443-tcp
          protocol: TCP
          port: 8443
          targetPort: 8443
        - name: 8778-tcp
          protocol: TCP
          port: 8778
          targetPort: 8778
      selector:
        app: placeholder-app-label-d46881878f594a2dadfd963843452aab
        deploymentconfig: fuse-cxf-amq-example
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Route
    metadata:
      name: fuse-cxf-amq-example
      labels:
        app: fuse-cxf-amq-example
    spec:
      port:
        targetPort: 8080-tcp
      to:
        kind: Service
        name: fuse-cxf-amq-example
